# use_frameworks!

platform :ios, '8.0'

target 'LWContactManager_Example' do
  pod 'LWContactManager', :path => '../'

  pod 'APAddressBook', '0.3.2'

  # target 'LWContactManager_Tests' do
  #   inherit! :search_paths
  # end
end
